import type {
  CrisisZone,
  Donation,
  NotificationModel,
  Recipient,
  RouteModel,
  Volunteer,
} from "./types";

export const donations: Donation[] = [
  {
    id: "d-100",
    title: "Cooked rice + dal trays",
    category: "Meal Packs",
    foodType: "cooked",
    dietType: "veg",
    quantity: "42 kg",
    estimatedMeals: 110,
    donor: { id: "u-d1", name: "Green Spoon Kitchen", reliabilityScore: 92 },
    status: "assigned",
    safetyStatus: "safe",
    readinessScore: 89,
    nutritionTags: ["balanced meal", "protein-rich", "child-friendly"],
    allergens: ["none"],
    createdAt: "2026-03-28T10:10:00Z",
    expiresAt: "2026-03-28T14:00:00Z",
    pickupLocation: { lat: 12.9658, lng: 77.6014, address: "14 Residency Rd", zone: "Central" },
    assignedVolunteer: "v-11",
    assignedRecipient: "r-22",
    urgency: "high",
  },
  {
    id: "d-101",
    title: "Packaged sandwich boxes",
    category: "Packaged Food",
    foodType: "packaged",
    dietType: "egg",
    quantity: "18 boxes",
    estimatedMeals: 36,
    donor: { id: "u-d2", name: "Metro Cafe", reliabilityScore: 86 },
    status: "matched",
    safetyStatus: "pickup_soon",
    readinessScore: 77,
    nutritionTags: ["high-carb", "low shelf life"],
    allergens: ["gluten", "egg"],
    createdAt: "2026-03-28T11:00:00Z",
    expiresAt: "2026-03-28T13:30:00Z",
    pickupLocation: { lat: 12.9722, lng: 77.5896, address: "3 MG Road", zone: "North" },
    assignedRecipient: "r-20",
    urgency: "critical",
  },
  {
    id: "d-102",
    title: "Vegetable curry bulk",
    category: "Bulk Pots",
    foodType: "cooked",
    dietType: "veg",
    quantity: "55 kg",
    estimatedMeals: 140,
    donor: { id: "u-d3", name: "Harvest Caterers", reliabilityScore: 95 },
    status: "pending",
    safetyStatus: "safe",
    readinessScore: 91,
    nutritionTags: ["balanced meal", "elderly-friendly"],
    allergens: ["dairy"],
    createdAt: "2026-03-28T09:35:00Z",
    expiresAt: "2026-03-28T16:00:00Z",
    pickupLocation: { lat: 12.9544, lng: 77.6121, address: "21 Lakeview Ave", zone: "South" },
    urgency: "medium",
  },
];

export const recipients: Recipient[] = [
  {
    id: "r-20",
    name: "City Night Shelter",
    organization: "Urban Care Trust",
    capacity: 240,
    acceptsCooked: true,
    acceptsPackaged: true,
    refrigerationAvailable: true,
    nutritionPreferences: ["protein-rich", "child-friendly"],
    location: { lat: 12.9783, lng: 77.5968, address: "44 Civic Lane", zone: "North" },
    open: true,
    verified: true,
  },
  {
    id: "r-22",
    name: "Helping Hands NGO",
    organization: "Helping Hands",
    capacity: 180,
    acceptsCooked: true,
    acceptsPackaged: true,
    refrigerationAvailable: false,
    nutritionPreferences: ["balanced meal", "elderly-friendly"],
    location: { lat: 12.9582, lng: 77.5979, address: "9 Chapel Street", zone: "Central" },
    open: true,
    verified: true,
  },
];

export const volunteers: Volunteer[] = [
  {
    id: "v-11",
    name: "Ravi N",
    vehicleType: "scooter",
    reliabilityScore: 94,
    availabilityStatus: "assigned",
    location: { lat: 12.9612, lng: 77.6053, address: "2 Brigade Rd", zone: "Central" },
  },
  {
    id: "v-13",
    name: "Anita P",
    vehicleType: "van",
    reliabilityScore: 91,
    availabilityStatus: "available",
    location: { lat: 12.9766, lng: 77.5821, address: "18 Richmond Town", zone: "West" },
  },
];

export const activeRoute: RouteModel = {
  id: "rt-1",
  distance: 7.4,
  duration: 28,
  geometry: [
    { lat: 12.9612, lng: 77.6053 },
    { lat: 12.9658, lng: 77.6014 },
    { lat: 12.9582, lng: 77.5979 },
  ],
  steps: [
    { label: "Go to donor", etaMinutes: 8 },
    { label: "Confirm pickup", etaMinutes: 3 },
    { label: "Go to recipient", etaMinutes: 15 },
    { label: "Confirm delivery", etaMinutes: 2 },
  ],
  start: { lat: 12.9612, lng: 77.6053, address: "2 Brigade Rd" },
  end: { lat: 12.9582, lng: 77.5979, address: "9 Chapel Street" },
};

export const notifications: NotificationModel[] = [
  {
    id: "n-1",
    type: "assignment",
    title: "Volunteer assigned",
    message: "Ravi N assigned to donation d-100.",
    createdAt: "2 min ago",
    read: false,
    relatedPath: "/dashboard/volunteer",
  },
  {
    id: "n-2",
    type: "urgent",
    title: "Critical pickup window",
    message: "Sandwich boxes expire in 90 minutes.",
    createdAt: "7 min ago",
    read: false,
    relatedPath: "/dashboard/donor",
  },
  {
    id: "n-3",
    type: "delivery",
    title: "Delivery confirmed",
    message: "Donation d-093 marked delivered.",
    createdAt: "22 min ago",
    read: true,
    relatedPath: "/dashboard/recipient",
  },
];

export const crisisZones: CrisisZone[] = [
  {
    id: "c-1",
    zone: "North Cluster",
    severity: "high",
    reason: "Demand spike due to shelter influx",
    impactedRecipients: 5,
    lat: 12.9792,
    lng: 77.5931,
    radiusKm: 2.4,
    active: true,
  },
  {
    id: "c-2",
    zone: "East River Belt",
    severity: "critical",
    reason: "Flood impact and transport delay",
    impactedRecipients: 8,
    lat: 12.969,
    lng: 77.6265,
    radiusKm: 3.1,
    active: true,
  },
];

export const impactSeries = [
  { day: "Mon", meals: 220, kg: 88 },
  { day: "Tue", meals: 260, kg: 96 },
  { day: "Wed", meals: 310, kg: 112 },
  { day: "Thu", meals: 280, kg: 106 },
  { day: "Fri", meals: 360, kg: 132 },
  { day: "Sat", meals: 405, kg: 148 },
  { day: "Sun", meals: 330, kg: 124 },
];
